name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build
        run: |
          npm install
          npm run build
      - uses: actions/checkout@v2
      - name: Commit report
        run: |
          git config --global user.name simmzl
          git config --global user.email 27859920+simmzl@users.noreply.github.com 
          git commit -am "chore(actions): Automated report"
          git push
